// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjymowjrqidmgslauauv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeW1vd2pycWlkbWdzbGF1YXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTg5NDksImV4cCI6MjA2NTUzNDk0OX0.Vgr0rW3Xi6eoD-hKX5R_4IeL5ABNPP0w80EUVzUAG8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);